data_paths:
  train_root_dir: /opt/ml/input/data/eval_dataset
  eval_root_dir: /opt/ml/input/data/train_dataset
  training_dialogue_file: train_dials.json
  training_ontology_file: ontology.json
  training_slot_meta_file: slot_meta.json
  evaluation_dialogue_file: eval_dials.json
  evaluation_slot_meta_file: slot_meta.json

save_paths:
  root_dir: ./results/
  checkpoints_dir: checkpoint/
  tensorboard_log_dir: tensorboard/
  yaml_log_dir: yaml_log/

hyperparameters:
  seed: 327459
  train_batch_size: 32
  dev_batch_size: 64
  dev_split:
    split_k: 10
    target: 7   # 0 ~ 5 지하철 도메인 dev셋에 없음
  model:
    name: TRADE
    backbone:
      bert: 1
    args:
      hidden_dropout_prob: 0.1
      hidden_size: 768
      proj_dim: null
  optimizer:
    name: AdamW
    args:
      lr: 0.0001
  epochs: 32
trainee_name: PBT_1
trainee_type: BertTradeTrainee
